# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8JX0lIQkXSyxN8NOSZNdT2xks7b9DFt
"""

from deliverable2 import *

# Instantiate the URLValidator class
validator = URLValidator()

# Define queries and URLs
queries_and_urls = [
    ("How blockchain works", "https://www.ibm.com/topics/what-is-blockchain"),
    ("Climate change effects", "https://www.nationalgeographic.com/environment/article/climate-change-overview"),
    ("COVID-19 vaccine effectiveness", "https://www.cdc.gov/coronavirus/2019-ncov/vaccines/effectiveness.html"),
    ("Latest AI advancements", "https://www.technologyreview.com/topic/artificial-intelligence"),
    ("Stock market trends", "https://www.bloomberg.com/markets"),
    ("Healthy diet tips", "https://www.healthline.com/nutrition/healthy-eating-tips"),
    ("Space exploration missions", "https://www.nasa.gov/missions"),
    ("Electric vehicle benefits", "https://www.tesla.com/benefits"),
    ("History of the internet", "https://www.history.com/topics/inventions/history-of-the-internet"),
    ("Nutritional benefits of a vegan diet", "https://www.hsph.harvard.edu/nutritionsource/healthy-weight/diet-reviews/vegan-diet/"),
    ("Mental health awareness", "https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response")
]

# Run validation for each URL and print the results
import json

for user_prompt, url_to_check in queries_and_urls:
    result = validator.rate_url_validity(user_prompt, url_to_check)
    print(f"Query: {user_prompt}")
    print(f"URL: {url_to_check}")
    print(json.dumps(result, indent=2))
    print("\n" + "="*80 + "\n")  # Separator for readability